services:
  web:
    build: .
    ports:
      - "5430:8000"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chropfchroette
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chropfchroette
    volumes:
      - ./postgres-data:/var/lib/postgresql/data