name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  wireguard:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - run: |
        sudo apt install wireguard
        echo "${{ secrets.WG_CONFIG_FILE }}" > wg0.conf
        sudo wg-quick up ./wg0.conf
      shell: bash

    # ssh into server using wireguard connection
    - name: SSH into server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "Connected to server via WireGuard"